/**
 * knowledgeBase.js
 * AUTO-GENERATED from knowledge_base.py — do not edit manually.
 * 125 diseases · 254 unique symptoms · 11 emergency rules
 * Sources: core clinical data + Kaggle augmented dataset
 */

export const DISEASES = {
  "Influenza (Flu)": {
    prior: 0.15,
    urgency: "Moderate",
    description: "Viral respiratory illness with rapid onset",
    symptoms: {
      "fever": 0.9,
      "cough": 0.85,
      "fatigue": 0.9,
      "muscle_ache": 0.85,
      "headache": 0.75,
      "sore_throat": 0.6,
      "runny_nose": 0.5,
      "chills": 0.8,
      "loss_of_appetite": 0.65,
      "shortness_of_breath": 0.2,
      "vomiting": 0.3,
      "diarrhea": 0.25,
      "sweating": 0.7,
      "weakness": 0.85,
    },
  },
  "COVID-19": {
    prior: 0.1,
    urgency: "Moderate",
    description: "SARS-CoV-2 respiratory infection with wide symptom range",
    symptoms: {
      "fever": 0.85,
      "cough": 0.75,
      "fatigue": 0.88,
      "loss_of_taste": 0.7,
      "loss_of_smell": 0.72,
      "shortness_of_breath": 0.45,
      "headache": 0.65,
      "muscle_ache": 0.7,
      "sore_throat": 0.5,
      "runny_nose": 0.35,
      "diarrhea": 0.3,
      "chills": 0.5,
      "chest_pain": 0.2,
      "confusion": 0.15,
      "loss_of_appetite": 0.6,
    },
  },
  "Common Cold": {
    prior: 0.25,
    urgency: "Low",
    description: "Mild viral upper respiratory tract infection",
    symptoms: {
      "runny_nose": 0.9,
      "sore_throat": 0.8,
      "cough": 0.7,
      "sneezing": 0.85,
      "headache": 0.5,
      "fever": 0.2,
      "fatigue": 0.55,
      "congestion": 0.88,
      "loss_of_appetite": 0.3,
      "watery_eyes": 0.6,
      "mild_body_ache": 0.4,
    },
  },
  "Pneumonia": {
    prior: 0.05,
    urgency: "Emergency",
    description: "Lung infection causing inflammation in air sacs",
    symptoms: {
      "fever": 0.8,
      "cough": 0.9,
      "shortness_of_breath": 0.85,
      "chest_pain": 0.75,
      "fatigue": 0.8,
      "chills": 0.75,
      "confusion": 0.35,
      "rapid_breathing": 0.8,
      "sweating": 0.65,
      "loss_of_appetite": 0.6,
      "bluish_lips": 0.2,
      "muscle_ache": 0.55,
    },
  },
  "Dengue Fever": {
    prior: 0.04,
    urgency: "Emergency",
    description: "Mosquito-borne viral disease common in tropical regions",
    symptoms: {
      "fever": 0.95,
      "severe_headache": 0.85,
      "muscle_ache": 0.9,
      "joint_pain": 0.88,
      "rash": 0.75,
      "nausea": 0.7,
      "vomiting": 0.65,
      "fatigue": 0.85,
      "loss_of_appetite": 0.7,
      "eye_pain": 0.8,
      "bleeding_gums": 0.3,
      "chills": 0.5,
    },
  },
  "Typhoid Fever": {
    prior: 0.04,
    urgency: "Emergency",
    description: "Bacterial infection from Salmonella typhi, requires antibiotics",
    symptoms: {
      "fever": 0.92,
      "headache": 0.8,
      "weakness": 0.85,
      "abdominal_pain": 0.75,
      "diarrhea": 0.6,
      "constipation": 0.45,
      "loss_of_appetite": 0.8,
      "nausea": 0.65,
      "rash": 0.3,
      "fatigue": 0.85,
      "muscle_ache": 0.7,
      "sweating": 0.55,
    },
  },
  "Gastroenteritis": {
    prior: 0.12,
    urgency: "Moderate",
    description: "Stomach and intestinal inflammation, often viral or bacterial",
    symptoms: {
      "nausea": 0.9,
      "vomiting": 0.85,
      "diarrhea": 0.9,
      "abdominal_pain": 0.85,
      "fever": 0.6,
      "loss_of_appetite": 0.75,
      "fatigue": 0.7,
      "dehydration": 0.65,
      "headache": 0.45,
      "muscle_ache": 0.4,
      "cramping": 0.8,
    },
  },
  "Malaria": {
    prior: 0.03,
    urgency: "Emergency",
    description: "Parasitic disease transmitted by Anopheles mosquitoes",
    symptoms: {
      "fever": 0.95,
      "chills": 0.9,
      "sweating": 0.88,
      "headache": 0.8,
      "muscle_ache": 0.75,
      "nausea": 0.7,
      "vomiting": 0.65,
      "fatigue": 0.85,
      "joint_pain": 0.6,
      "confusion": 0.25,
      "jaundice": 0.3,
      "rapid_breathing": 0.35,
    },
  },
  "Migraine": {
    prior: 0.1,
    urgency: "Low",
    description: "Neurological headache disorder with moderate to severe pain",
    symptoms: {
      "severe_headache": 0.95,
      "nausea": 0.7,
      "vomiting": 0.5,
      "sensitivity_to_light": 0.88,
      "sensitivity_to_sound": 0.8,
      "visual_aura": 0.4,
      "fatigue": 0.65,
      "neck_stiffness": 0.3,
      "dizziness": 0.55,
      "sweating": 0.35,
    },
  },
  "Urinary Tract Infection (UTI)": {
    prior: 0.08,
    urgency: "Moderate",
    description: "Bacterial infection affecting the urinary system",
    symptoms: {
      "painful_urination": 0.9,
      "frequent_urination": 0.88,
      "lower_abdominal_pain": 0.75,
      "blood_in_urine": 0.55,
      "fever": 0.5,
      "chills": 0.4,
      "fatigue": 0.55,
      "back_pain": 0.6,
      "nausea": 0.4,
      "foul_smelling_urine": 0.7,
    },
  },
  "Appendicitis": {
    prior: 0.03,
    urgency: "Emergency",
    description: "Inflammation of the appendix requiring urgent surgical treatment",
    symptoms: {
      "abdominal_pain": 0.95,
      "nausea": 0.85,
      "vomiting": 0.75,
      "fever": 0.7,
      "loss_of_appetite": 0.8,
      "constipation": 0.5,
      "diarrhea": 0.3,
      "abdominal_rigidity": 0.7,
      "rebound_tenderness": 0.8,
      "chills": 0.45,
    },
  },
  "Hypertensive Crisis": {
    prior: 0.02,
    urgency: "Emergency",
    description: "Dangerously high blood pressure requiring immediate treatment",
    symptoms: {
      "severe_headache": 0.9,
      "chest_pain": 0.75,
      "vision_changes": 0.65,
      "shortness_of_breath": 0.7,
      "nausea": 0.6,
      "confusion": 0.5,
      "nosebleed": 0.45,
      "anxiety": 0.55,
      "palpitations": 0.6,
      "sweating": 0.5,
    },
  },
  "Strep Throat": {
    prior: 0.07,
    urgency: "Moderate",
    description: "Bacterial throat infection caused by Streptococcus",
    symptoms: {
      "sore_throat": 0.95,
      "fever": 0.8,
      "difficulty_swallowing": 0.85,
      "headache": 0.65,
      "nausea": 0.45,
      "rash": 0.3,
      "swollen_lymph_nodes": 0.8,
      "loss_of_appetite": 0.6,
      "stomach_ache": 0.4,
      "vomiting": 0.35,
    },
  },
  "Asthma Attack": {
    prior: 0.05,
    urgency: "Emergency",
    description: "Airway inflammation causing breathing difficulty",
    symptoms: {
      "shortness_of_breath": 0.95,
      "wheezing": 0.9,
      "chest_tightness": 0.85,
      "cough": 0.8,
      "anxiety": 0.65,
      "difficulty_speaking": 0.55,
      "rapid_breathing": 0.8,
      "bluish_lips": 0.3,
      "sweating": 0.45,
    },
  },
  "Anemia": {
    prior: 0.06,
    urgency: "Moderate",
    description: "Insufficient red blood cells or hemoglobin in blood",
    symptoms: {
      "fatigue": 0.9,
      "weakness": 0.85,
      "shortness_of_breath": 0.7,
      "pale_skin": 0.8,
      "dizziness": 0.75,
      "headache": 0.6,
      "cold_hands_feet": 0.65,
      "chest_pain": 0.4,
      "palpitations": 0.55,
      "loss_of_appetite": 0.5,
    },
  },
  "Chickenpox": {
    prior: 0.04,
    urgency: "Moderate",
    description: "Viral infection causing itchy blister-like rash",
    symptoms: {
      "rash": 0.95,
      "fever": 0.7,
      "itching": 0.9,
      "fatigue": 0.65,
      "loss_of_appetite": 0.55,
    },
  },
  "Hepatitis B": {
    prior: 0.02,
    urgency: "Emergency",
    description: "Viral liver infection causing jaundice and fatigue",
    symptoms: {
      "jaundice": 0.8,
      "fatigue": 0.88,
      "nausea": 0.7,
      "abdominal_pain": 0.65,
      "fever": 0.5,
    },
  },
  "Acute Sinusitis": {
    prior: 0.08,
    urgency: "Low",
    description: "Inflammation of sinuses causing facial pain and congestion",
    symptoms: {
      "nasal_congestion": 0.9,
      "facial_pain": 0.85,
      "headache": 0.78,
      "runny_nose": 0.8,
      "fever": 0.3,
    },
  },
  "Meningitis": {
    prior: 0.01,
    urgency: "Emergency",
    description: "Infection of membranes surrounding brain and spinal cord",
    symptoms: {
      "severe_headache": 0.9,
      "fever": 0.85,
      "neck_stiffness": 0.88,
      "confusion": 0.65,
      "sensitivity_to_light": 0.75,
    },
  },
  "Leptospirosis": {
    prior: 0.02,
    urgency: "Emergency",
    description: "Bacterial infection from animal urine, common after floods",
    symptoms: {
      "fever": 0.9,
      "headache": 0.8,
      "muscle_ache": 0.85,
      "jaundice": 0.55,
      "rash": 0.35,
      "red_eyes": 0.65,
      "vomiting": 0.6,
      "abdominal_pain": 0.5,
    },
  },
  "Irritable Bowel Syndrome": {
    prior: 0.07,
    urgency: "Low",
    description: "Chronic GI disorder affecting large intestine",
    symptoms: {
      "abdominal_pain": 0.88,
      "bloating": 0.85,
      "diarrhea": 0.75,
      "constipation": 0.65,
      "cramping": 0.82,
      "nausea": 0.5,
      "fatigue": 0.55,
    },
  },
  "Heat Stroke": {
    prior: 0.02,
    urgency: "Emergency",
    description: "Life-threatening overheating of the body requiring immediate cooling",
    symptoms: {
      "fever": 0.95,
      "confusion": 0.8,
      "rapid_breathing": 0.75,
      "sweating": 0.7,
      "headache": 0.75,
      "nausea": 0.65,
      "weakness": 0.8,
      "loss_of_consciousness": 0.4,
    },
  },
  "Tinnitus Of Unknown Cause": {
    prior: 0.04,
    urgency: "Low",
    description: "Perception of ringing or noise in the ears without external source",
    symptoms: {
      "hoarse_voice": 0.78,
      "itchy_ears": 0.65,
      "ringing_in_ear": 0.54,
      "diminished_hearing": 0.53,
      "plugged_feeling_in_ear": 0.53,
      "dizziness": 0.53,
      "headache": 0.51,
      "ear_pain": 0.48,
    },
  },
  "Glaucoma": {
    prior: 0.03,
    urgency: "Moderate",
    description: "Optic nerve damage from elevated intraocular pressure",
    symptoms: {
      "foreign_body_sensation_in_eye": 0.67,
      "itchiness_of_eye": 0.66,
      "itchy_eyelid": 0.64,
      "lacrimation": 0.53,
      "symptoms_of_eye": 0.53,
      "spots_or_clouds_in_vision": 0.53,
      "eye_redness": 0.52,
      "diminished_vision": 0.52,
      "pain_in_eye": 0.51,
    },
  },
  "Transient Ischemic Attack": {
    prior: 0.02,
    urgency: "Emergency",
    description: "Brief episode of neurological dysfunction from temporary blood flow loss",
    symptoms: {
      "focal_weakness": 0.68,
      "depressive_or_psychotic_symptoms": 0.64,
      "headache": 0.54,
      "dizziness": 0.54,
      "loss_of_sensation": 0.53,
      "difficulty_speaking": 0.51,
      "symptoms_of_the_face": 0.5,
      "paresthesia": 0.49,
      "disturbance_of_memory": 0.48,
      "weakness": 0.48,
    },
  },
  "Pyelonephritis": {
    prior: 0.03,
    urgency: "Moderate",
    description: "Bacterial kidney infection requiring prompt antibiotic treatment",
    symptoms: {
      "sharp_abdominal_pain": 0.68,
      "low_back_pain": 0.52,
      "frequent_urination": 0.52,
      "side_pain": 0.52,
      "nausea": 0.51,
      "lower_abdominal_pain": 0.51,
      "painful_urination": 0.51,
      "blood_in_urine": 0.5,
      "vomiting": 0.5,
      "suprapubic_pain": 0.48,
      "back_pain": 0.47,
    },
  },
  "Cirrhosis": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Irreversible liver scarring from long-term damage",
    symptoms: {
      "vomiting_blood": 0.77,
      "blood_in_stool": 0.71,
      "upper_abdominal_pain": 0.69,
      "abdominal_distention": 0.55,
      "shortness_of_breath": 0.55,
      "peripheral_edema": 0.55,
      "regurgitation": 0.52,
      "regurgitation.1": 0.52,
      "sharp_abdominal_pain": 0.5,
    },
  },
  "Fibromyalgia": {
    prior: 0.04,
    urgency: "Low",
    description: "Widespread musculoskeletal pain with fatigue and sleep issues",
    symptoms: {
      "low_back_pain": 0.71,
      "hip_pain": 0.67,
      "leg_pain": 0.51,
      "arm_pain": 0.51,
      "muscle_pain": 0.51,
      "neck_pain": 0.51,
      "headache": 0.5,
      "ache_all_over": 0.5,
      "sharp_chest_pain": 0.5,
      "back_pain": 0.48,
    },
  },
  "Acute Pancreatitis": {
    prior: 0.02,
    urgency: "Emergency",
    description: "Sudden pancreatic inflammation causing severe abdominal pain",
    symptoms: {
      "burning_abdominal_pain": 0.53,
      "nausea": 0.52,
      "vomiting": 0.51,
      "abusing_alcohol": 0.51,
      "hemoptysis": 0.51,
      "diarrhea": 0.51,
      "upper_abdominal_pain": 0.5,
      "back_pain": 0.5,
      "sharp_abdominal_pain": 0.5,
      "lower_body_pain": 0.5,
      "side_pain": 0.49,
      "sharp_chest_pain": 0.49,
    },
  },
  "Asthma": {
    prior: 0.08,
    urgency: "Moderate",
    description: "Chronic airway inflammation causing variable breathing difficulty",
    symptoms: {
      "coughing_up_sputum": 0.67,
      "nasal_congestion": 0.53,
      "allergic_reaction": 0.53,
      "wheezing": 0.52,
      "cough": 0.52,
      "difficulty_breathing": 0.51,
      "fever": 0.51,
      "sharp_chest_pain": 0.51,
      "coryza": 0.51,
      "chest_tightness": 0.48,
      "shortness_of_breath": 0.48,
    },
  },
  "Restless Leg Syndrome": {
    prior: 0.04,
    urgency: "Low",
    description: "Urge to move legs with uncomfortable sensations at rest",
    symptoms: {
      "insomnia": 0.81,
      "fatigue": 0.67,
      "headache": 0.53,
      "abnormal_involuntary_movements": 0.51,
      "sleepiness": 0.5,
      "depression": 0.5,
      "leg_pain": 0.5,
      "apnea": 0.48,
    },
  },
  "Stroke": {
    prior: 0.03,
    urgency: "Emergency",
    description: "Interrupted blood supply to brain causing neurological damage",
    symptoms: {
      "headache": 0.74,
      "problems_with_movement": 0.69,
      "focal_weakness": 0.53,
      "dizziness": 0.52,
      "slurring_words": 0.52,
      "seizures": 0.51,
      "abnormal_involuntary_movements": 0.51,
      "difficulty_speaking": 0.5,
      "disturbance_of_memory": 0.5,
      "depressive_or_psychotic_symptoms": 0.5,
    },
  },
  "Atrial Fibrillation": {
    prior: 0.04,
    urgency: "Moderate",
    description: "Irregular rapid heart rhythm originating in the atria",
    symptoms: {
      "palpitations": 0.65,
      "dizziness": 0.62,
      "increased_heart_rate": 0.6,
      "shortness_of_breath": 0.59,
      "sharp_chest_pain": 0.54,
      "decreased_heart_rate": 0.53,
      "fatigue": 0.53,
      "irregular_heartbeat": 0.49,
    },
  },
  "Chronic Obstructive Pulmonary Disease (COPD)": {
    prior: 0.05,
    urgency: "Moderate",
    description: "Progressive airflow limitation from airway/alveolar abnormality",
    symptoms: {
      "sharp_chest_pain": 0.69,
      "coryza": 0.53,
      "coughing_up_sputum": 0.53,
      "cough": 0.53,
      "nasal_congestion": 0.52,
      "wheezing": 0.52,
      "congestion_in_chest": 0.5,
      "fever": 0.5,
      "sore_throat": 0.5,
      "shortness_of_breath": 0.49,
      "chest_tightness": 0.48,
    },
  },
  "Deep Vein Thrombosis (DVT)": {
    prior: 0.03,
    urgency: "Emergency",
    description: "Blood clot forming in a deep vein, usually in the leg",
    symptoms: {
      "leg_cramps_or_spasms": 0.77,
      "abnormal_appearing_skin": 0.69,
      "leg_stiffness_or_tightness": 0.68,
      "arm_swelling": 0.68,
      "leg_pain": 0.53,
      "leg_swelling": 0.53,
      "foot_or_toe_swelling": 0.51,
    },
  },
  "Pericarditis": {
    prior: 0.02,
    urgency: "Emergency",
    description: "Inflammation of the pericardium surrounding the heart",
    symptoms: {
      "palpitations": 0.8,
      "lower_body_pain": 0.76,
      "chest_tightness": 0.75,
      "sharp_abdominal_pain": 0.7,
      "shortness_of_breath": 0.63,
      "sharp_chest_pain": 0.54,
    },
  },
  "Attention Deficit Hyperactivity Disorder (ADHD)": {
    prior: 0.05,
    urgency: "Moderate",
    description: "Neurodevelopmental disorder with inattention and hyperactivity",
    symptoms: {
      "hostile_behavior": 0.69,
      "lack_of_growth": 0.66,
      "drug_abuse": 0.64,
      "antisocial_behavior": 0.52,
      "depression": 0.52,
      "temper_problems": 0.52,
      "depressive_or_psychotic_symptoms": 0.49,
      "anxiety_and_nervousness": 0.49,
      "restlessness": 0.49,
    },
  },
  "Hypothyroidism": {
    prior: 0.06,
    urgency: "Moderate",
    description: "Underactive thyroid gland producing insufficient thyroid hormone",
    symptoms: {
      "wrist_swelling": 0.88,
      "hot_flashes": 0.72,
      "fatigue": 0.58,
      "weight_gain": 0.57,
      "too_little_hair": 0.54,
      "muscle_pain": 0.47,
    },
  },
  "Vitamin B12 Deficiency": {
    prior: 0.05,
    urgency: "Low",
    description: "Deficiency causing anaemia and neurological symptoms",
    symptoms: {
      "knee_stiffness_or_tightness": 0.8,
      "hot_flashes": 0.76,
      "disturbance_of_memory": 0.72,
      "problems_with_movement": 0.53,
      "fatigue": 0.53,
    },
  },
  "Endometriosis": {
    prior: 0.04,
    urgency: "Moderate",
    description: "Uterine tissue growing outside the uterus causing pain",
    symptoms: {
      "hot_flashes": 0.8,
      "lower_abdominal_pain": 0.54,
      "burning_abdominal_pain": 0.53,
      "infertility": 0.52,
      "intermenstrual_bleeding": 0.52,
      "painful_menstruation": 0.51,
      "pelvic_pain": 0.51,
      "sharp_abdominal_pain": 0.5,
      "heavy_menstrual_flow": 0.49,
    },
  },
  "Chronic Kidney Disease": {
    prior: 0.06,
    urgency: "Moderate",
    description: "Progressive loss of kidney function over months or years",
    symptoms: {
      "fatigue": 0.8,
      "feeling_cold": 0.7,
      "peripheral_edema": 0.6,
      "symptoms_of_the_kidneys": 0.5,
      "shortness_of_breath": 0.4,
    },
  },
  "Bipolar Disorder": {
    prior: 0.03,
    urgency: "Moderate",
    description: "Mood disorder with episodes of mania and depression",
    symptoms: {
      "insomnia": 0.67,
      "abusing_alcohol": 0.65,
      "depression": 0.52,
      "delusions_or_hallucinations": 0.52,
      "depressive_or_psychotic_symptoms": 0.51,
      "excessive_anger": 0.51,
      "obsessions_and_compulsions": 0.51,
      "fears_and_phobias": 0.51,
      "anxiety_and_nervousness": 0.49,
      "temper_problems": 0.48,
    },
  },
  "Hypoglycemia": {
    prior: 0.04,
    urgency: "Moderate",
    description: "Abnormally low blood sugar causing neurological symptoms",
    symptoms: {
      "nausea": 0.51,
      "feeling_ill": 0.51,
      "seizures": 0.51,
      "fainting": 0.51,
      "sweating": 0.51,
      "abnormal_involuntary_movements": 0.5,
      "sleepiness": 0.5,
      "dizziness": 0.5,
      "weakness": 0.5,
      "problems_with_movement": 0.5,
      "decreased_appetite": 0.48,
      "depressive_or_psychotic_symptoms": 0.48,
    },
  },
  "Plantar Fasciitis": {
    prior: 0.04,
    urgency: "Low",
    description: "Inflammation of plantar fascia causing heel pain",
    symptoms: {
      "muscle_pain": 0.78,
      "problems_with_movement": 0.67,
      "bones_are_painful": 0.66,
      "knee_pain": 0.57,
      "foot_or_toe_pain": 0.57,
      "ankle_pain": 0.52,
      "ankle_swelling": 0.49,
    },
  },
  "Meniere Disease": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Inner ear disorder with vertigo, hearing loss, and tinnitus",
    symptoms: {
      "facial_pain": 0.78,
      "ear_pain": 0.67,
      "ringing_in_ear": 0.52,
      "nausea": 0.52,
      "dizziness": 0.51,
      "diminished_hearing": 0.51,
      "headache": 0.5,
      "allergic_reaction": 0.49,
    },
  },
  "Sciatica": {
    prior: 0.06,
    urgency: "Low",
    description: "Sciatic nerve compression causing radiating leg pain",
    symptoms: {
      "leg_pain": 0.67,
      "problems_with_movement": 0.67,
      "lower_body_pain": 0.53,
      "low_back_pain": 0.53,
      "leg_weakness": 0.52,
      "loss_of_sensation": 0.52,
      "hip_pain": 0.5,
      "back_cramps_or_spasms": 0.49,
      "unusual_color_or_odor_to_urine": 0.48,
      "leg_cramps_or_spasms": 0.47,
    },
  },
  "Varicose Veins": {
    prior: 0.05,
    urgency: "Low",
    description: "Enlarged twisted veins usually in the legs",
    symptoms: {
      "leg_cramps_or_spasms": 0.74,
      "ache_all_over": 0.54,
      "leg_swelling": 0.53,
      "skin_lesion": 0.52,
      "leg_lump_or_mass": 0.5,
      "leg_pain": 0.5,
      "peripheral_edema": 0.47,
      "lymphedema": 0.44,
    },
  },
  "Pulmonary Fibrosis": {
    prior: 0.01,
    urgency: "Moderate",
    description: "Lung tissue scarring leading to progressive breathing difficulty",
    symptoms: {
      "chest_tightness": 0.86,
      "fever": 0.58,
      "shortness_of_breath": 0.57,
      "sharp_chest_pain": 0.57,
      "fainting": 0.56,
      "cough": 0.54,
      "difficulty_breathing": 0.49,
    },
  },
  "Parkinson Disease": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Progressive nervous system disorder affecting movement",
    symptoms: {
      "focal_weakness": 0.68,
      "stiffness_all_over": 0.67,
      "leg_stiffness_or_tightness": 0.67,
      "abnormal_involuntary_movements": 0.52,
      "weakness": 0.51,
      "difficulty_speaking": 0.49,
      "dizziness": 0.48,
      "disturbance_of_memory": 0.47,
      "problems_with_movement": 0.45,
    },
  },
  "Gout": {
    prior: 0.04,
    urgency: "Low",
    description: "Painful arthritis from uric acid crystal deposition in joints",
    symptoms: {
      "knee_pain": 0.53,
      "foot_or_toe_pain": 0.52,
      "knee_swelling": 0.52,
      "foot_or_toe_swelling": 0.52,
      "ankle_pain": 0.51,
      "wrist_swelling": 0.51,
      "ankle_swelling": 0.51,
      "hand_or_finger_swelling": 0.5,
      "wrist_pain": 0.5,
      "joint_pain": 0.5,
      "hand_or_finger_pain": 0.48,
      "leg_swelling": 0.47,
    },
  },
  "Food Allergy": {
    prior: 0.06,
    urgency: "Low",
    description: "Immune response to specific food proteins",
    symptoms: {
      "lip_swelling": 0.74,
      "cough": 0.69,
      "allergic_reaction": 0.53,
      "abnormal_appearing_skin": 0.52,
      "itching_of_skin": 0.51,
      "hand_or_finger_swelling": 0.51,
      "vomiting": 0.49,
      "skin_rash": 0.49,
      "nasal_congestion": 0.49,
    },
  },
  "Anxiety": {
    prior: 0.12,
    urgency: "Moderate",
    description: "Excessive worry and fear causing physical and psychological symptoms",
    symptoms: {
      "sharp_chest_pain": 0.53,
      "depressive_or_psychotic_symptoms": 0.52,
      "insomnia": 0.52,
      "depression": 0.51,
      "abnormal_involuntary_movements": 0.51,
      "headache": 0.51,
      "irregular_heartbeat": 0.51,
      "shortness_of_breath": 0.51,
      "fears_and_phobias": 0.51,
      "palpitations": 0.5,
      "increased_heart_rate": 0.49,
      "anxiety_and_nervousness": 0.49,
    },
  },
  "Bell Palsy": {
    prior: 0.01,
    urgency: "Moderate",
    description: "Sudden temporary facial muscle weakness from nerve inflammation",
    symptoms: {
      "diminished_vision": 0.66,
      "abnormal_involuntary_movements": 0.64,
      "peripheral_edema": 0.52,
      "focal_weakness": 0.52,
      "symptoms_of_eye": 0.52,
      "symptoms_of_the_face": 0.51,
      "facial_pain": 0.5,
      "headache": 0.49,
      "weakness": 0.49,
      "loss_of_sensation": 0.48,
    },
  },
  "Osteoarthritis": {
    prior: 0.1,
    urgency: "Low",
    description: "Degenerative joint disease with cartilage breakdown",
    symptoms: {
      "hip_pain": 0.69,
      "knee_weakness": 0.52,
      "knee_pain": 0.52,
      "ankle_pain": 0.52,
      "muscle_pain": 0.51,
      "knee_swelling": 0.51,
      "elbow_pain": 0.51,
      "back_pain": 0.5,
      "leg_pain": 0.5,
      "hand_or_finger_pain": 0.5,
      "joint_pain": 0.49,
    },
  },
  "Macular Degeneration": {
    prior: 0.03,
    urgency: "Low",
    description: "Deterioration of central retina causing vision loss",
    symptoms: {
      "double_vision": 0.67,
      "foreign_body_sensation_in_eye": 0.54,
      "blindness": 0.52,
      "lacrimation": 0.51,
      "abnormal_movement_of_eyelid": 0.51,
      "bleeding_from_eye": 0.5,
      "spots_or_clouds_in_vision": 0.5,
      "pain_in_eye": 0.5,
      "diminished_vision": 0.5,
      "itchiness_of_eye": 0.49,
      "symptoms_of_eye": 0.49,
    },
  },
  "Gonorrhea": {
    prior: 0.03,
    urgency: "Moderate",
    description: "Bacterial STI affecting mucous membranes",
    symptoms: {
      "problems_with_movement": 0.86,
      "vaginal_pain": 0.73,
      "vaginal_itching": 0.69,
      "sharp_abdominal_pain": 0.6,
      "penile_discharge": 0.56,
      "vaginal_discharge": 0.5,
    },
  },
  "Carpal Tunnel Syndrome": {
    prior: 0.05,
    urgency: "Low",
    description: "Median nerve compression causing hand pain and numbness",
    symptoms: {
      "elbow_pain": 0.68,
      "wrist_swelling": 0.53,
      "loss_of_sensation": 0.52,
      "neck_pain": 0.52,
      "wrist_pain": 0.52,
      "paresthesia": 0.52,
      "hand_or_finger_stiffness_or_tightness": 0.51,
      "arm_pain": 0.5,
      "arm_weakness": 0.5,
      "hand_or_finger_pain": 0.5,
      "hand_or_finger_swelling": 0.49,
    },
  },
  "Kidney Stone": {
    prior: 0.05,
    urgency: "Moderate",
    description: "Hard mineral deposits forming in kidneys causing severe pain",
    symptoms: {
      "vomiting": 0.71,
      "back_pain": 0.53,
      "side_pain": 0.52,
      "frequent_urination": 0.51,
      "painful_urination": 0.51,
      "low_back_pain": 0.51,
      "suprapubic_pain": 0.5,
      "sharp_abdominal_pain": 0.49,
      "lower_abdominal_pain": 0.49,
      "retention_of_urine": 0.48,
      "blood_in_urine": 0.48,
    },
  },
  "Syphilis": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Bacterial STI with stages from sore to systemic involvement",
    symptoms: {
      "muscle_pain": 0.97,
      "vaginal_discharge": 0.8,
      "skin_rash": 0.63,
      "headache": 0.57,
    },
  },
  "Kidney Failure": {
    prior: 0.02,
    urgency: "Emergency",
    description: "Kidneys unable to filter waste from blood adequately",
    symptoms: {
      "swollen_abdomen": 0.77,
      "sharp_chest_pain": 0.69,
      "nausea": 0.54,
      "arm_swelling": 0.51,
      "vomiting": 0.51,
      "shortness_of_breath": 0.5,
      "symptoms_of_the_kidneys": 0.5,
      "leg_swelling": 0.49,
    },
  },
  "Scarlet Fever": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Streptococcal infection with fever and characteristic rash",
    symptoms: {
      "throat_swelling": 0.86,
      "skin_swelling": 0.7,
      "fever": 0.61,
      "skin_rash": 0.52,
      "sore_throat": 0.49,
      "cough": 0.44,
    },
  },
  "Polycystic Ovarian Syndrome (PCOS)": {
    prior: 0.05,
    urgency: "Moderate",
    description: "Hormonal disorder causing enlarged ovaries with small cysts",
    symptoms: {
      "hot_flashes": 0.83,
      "absence_of_menstruation": 0.7,
      "long_menstrual_periods": 0.54,
      "unpredictable_menstruation": 0.54,
      "weight_gain": 0.53,
      "infertility": 0.53,
      "pelvic_pain": 0.5,
      "intermenstrual_bleeding": 0.49,
    },
  },
  "Seasonal Allergies (Hay Fever)": {
    prior: 0.1,
    urgency: "Low",
    description: "Allergic rhinitis triggered by airborne seasonal allergens",
    symptoms: {
      "lacrimation": 0.68,
      "ear_pain": 0.53,
      "frontal_headache": 0.52,
      "coryza": 0.51,
      "headache": 0.51,
      "allergic_reaction": 0.51,
      "sneezing": 0.51,
      "cough": 0.5,
      "nasal_congestion": 0.49,
      "sore_throat": 0.49,
      "itchiness_of_eye": 0.49,
    },
  },
  "Whooping Cough": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Highly contagious bacterial respiratory infection",
    symptoms: {
      "nasal_congestion": 0.93,
      "sore_throat": 0.84,
      "shortness_of_breath": 0.72,
      "vomiting": 0.7,
      "cough": 0.6,
    },
  },
  "Intracerebral Hemorrhage": {
    prior: 0.01,
    urgency: "Emergency",
    description: "Bleeding within the brain tissue from ruptured vessel",
    symptoms: {
      "diminished_vision": 0.78,
      "focal_weakness": 0.52,
      "nausea": 0.5,
      "headache": 0.5,
      "seizures": 0.5,
      "weakness": 0.5,
      "blindness": 0.49,
      "dizziness": 0.49,
      "depressive_or_psychotic_symptoms": 0.48,
      "vomiting": 0.47,
    },
  },
  "Alzheimer Disease": {
    prior: 0.03,
    urgency: "Moderate",
    description: "Progressive brain disorder destroying memory and cognitive function",
    symptoms: {
      "eye_burns_or_stings": 0.75,
      "hostile_behavior": 0.68,
      "irregular_appearing_scalp": 0.68,
      "depressive_or_psychotic_symptoms": 0.55,
      "difficulty_speaking": 0.54,
      "delusions_or_hallucinations": 0.54,
      "disturbance_of_memory": 0.53,
      "depression": 0.51,
    },
  },
  "Systemic Lupus Erythematosis (SLE)": {
    prior: 0.01,
    urgency: "Moderate",
    description: "Systemic autoimmune disease affecting multiple organs",
    symptoms: {
      "hand_or_finger_stiffness_or_tightness": 0.77,
      "bones_are_painful": 0.77,
      "knee_pain": 0.69,
      "leg_swelling": 0.67,
      "sharp_chest_pain": 0.56,
      "ache_all_over": 0.55,
    },
  },
  "Crohn Disease": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Chronic inflammatory bowel disease affecting any GI tract segment",
    symptoms: {
      "pain_of_the_anus": 0.78,
      "nausea": 0.54,
      "sharp_abdominal_pain": 0.53,
      "vomiting": 0.5,
      "regurgitation.1": 0.5,
      "regurgitation": 0.5,
      "burning_abdominal_pain": 0.49,
      "diarrhea": 0.49,
      "blood_in_stool": 0.49,
      "rectal_bleeding": 0.45,
    },
  },
  "Heart Attack": {
    prior: 0.04,
    urgency: "Emergency",
    description: "Blocked coronary artery causing myocardial cell death",
    symptoms: {
      "heartburn": 0.65,
      "fainting": 0.54,
      "nausea": 0.53,
      "increased_heart_rate": 0.52,
      "arm_pain": 0.51,
      "burning_chest_pain": 0.51,
      "irregular_heartbeat": 0.5,
      "shortness_of_breath": 0.5,
      "chest_tightness": 0.49,
      "sweating": 0.49,
      "sharp_chest_pain": 0.49,
    },
  },
  "Obstructive SLEep Apnea (OSA)": {
    prior: 0.06,
    urgency: "Low",
    description: "Repeated upper airway collapse during sleep",
    symptoms: {
      "mouth_dryness": 0.53,
      "fatigue": 0.52,
      "sweating": 0.52,
      "difficulty_breathing": 0.51,
      "abnormal_breathing_sounds": 0.51,
      "abnormal_involuntary_movements": 0.51,
      "apnea": 0.51,
      "weight_gain": 0.51,
      "difficulty_in_swallowing": 0.5,
      "insomnia": 0.5,
      "sleepiness": 0.5,
      "shortness_of_breath": 0.48,
    },
  },
  "Psoriasis": {
    prior: 0.04,
    urgency: "Low",
    description: "Autoimmune skin condition with scaly plaques",
    symptoms: {
      "skin_swelling": 0.65,
      "skin_rash": 0.55,
      "irregular_appearing_scalp": 0.54,
      "itchy_scalp": 0.51,
      "skin_growth": 0.51,
      "skin_moles": 0.51,
      "itching_of_skin": 0.5,
      "skin_dryness_peeling_scaliness_or_roughness": 0.5,
      "abnormal_appearing_skin": 0.5,
      "joint_pain": 0.49,
      "skin_lesion": 0.49,
    },
  },
  "Osteoporosis": {
    prior: 0.05,
    urgency: "Low",
    description: "Reduced bone density increasing fracture risk",
    symptoms: {
      "leg_cramps_or_spasms": 0.78,
      "disturbance_of_memory": 0.55,
      "early_or_late_onset_of_menopause": 0.54,
      "back_pain": 0.53,
      "bones_are_painful": 0.51,
      "hip_pain": 0.49,
      "joint_pain": 0.49,
      "stomach_bloating": 0.48,
      "muscle_cramps_contractures_or_spasms": 0.47,
    },
  },
  "Vitamin D Deficiency": {
    prior: 0.08,
    urgency: "Low",
    description: "Insufficient vitamin D causing bone weakness and immune dysfunction",
    symptoms: {
      "arm_stiffness_or_tightness": 0.94,
      "hot_flashes": 0.82,
      "fatigue": 0.65,
    },
  },
  "Tuberculosis": {
    prior: 0.03,
    urgency: "Moderate",
    description: "Bacterial lung infection caused by Mycobacterium tuberculosis",
    symptoms: {
      "vaginal_itching": 0.87,
      "cough": 0.65,
      "congestion_in_chest": 0.65,
      "shortness_of_breath": 0.48,
    },
  },
  "Benign Prostatic Hyperplasia (BPH)": {
    prior: 0.06,
    urgency: "Low",
    description: "Non-cancerous prostate enlargement causing urinary symptoms",
    symptoms: {
      "symptoms_of_prostate": 0.52,
      "frequent_urination": 0.52,
      "blood_in_urine": 0.51,
      "impotence": 0.5,
      "symptoms_of_bladder": 0.5,
      "low_urine_output": 0.5,
      "swelling_of_scrotum": 0.5,
      "pain_in_testicles": 0.5,
      "hesitancy": 0.5,
      "involuntary_urination": 0.5,
      "retention_of_urine": 0.5,
      "excessive_urination_at_night": 0.49,
    },
  },
  "Cataract": {
    prior: 0.06,
    urgency: "Low",
    description: "Clouding of the eye lens causing vision impairment",
    symptoms: {
      "double_vision": 0.72,
      "symptoms_of_eye": 0.52,
      "blindness": 0.52,
      "lacrimation": 0.51,
      "cloudy_eye": 0.51,
      "pain_in_eye": 0.5,
      "spots_or_clouds_in_vision": 0.49,
      "abnormal_movement_of_eyelid": 0.49,
      "itchiness_of_eye": 0.47,
      "diminished_vision": 0.46,
    },
  },
  "Myocarditis": {
    prior: 0.01,
    urgency: "Emergency",
    description: "Inflammation of the myocardium affecting heart function",
    symptoms: {
      "sharp_chest_pain": 1.0,
      "dizziness": 1.0,
      "palpitations": 1.0,
    },
  },
  "Preeclampsia": {
    prior: 0.01,
    urgency: "Emergency",
    description: "Pregnancy complication with high blood pressure and organ damage",
    symptoms: {
      "vaginal_redness": 0.67,
      "pain_during_pregnancy": 0.58,
      "uterine_contractions": 0.53,
      "headache": 0.53,
      "sharp_abdominal_pain": 0.53,
      "problems_during_pregnancy": 0.53,
      "spots_or_clouds_in_vision": 0.5,
      "lower_abdominal_pain": 0.5,
      "recent_pregnancy": 0.47,
    },
  },
  "Erectile Dysfunction": {
    prior: 0.05,
    urgency: "Low",
    description: "Inability to achieve or maintain erection adequate for intercourse",
    symptoms: {
      "involuntary_urination": 0.76,
      "loss_of_sex_drive": 0.54,
      "symptoms_of_prostate": 0.52,
      "frequent_urination": 0.52,
      "impotence": 0.51,
      "blood_in_urine": 0.51,
      "excessive_urination_at_night": 0.51,
      "pain_during_intercourse": 0.49,
      "pain_in_testicles": 0.48,
      "retention_of_urine": 0.47,
    },
  },
  "Lyme Disease": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Tick-borne bacterial infection causing rash and systemic symptoms",
    symptoms: {
      "hip_pain": 0.83,
      "depressive_or_psychotic_symptoms": 0.69,
      "headache": 0.68,
      "fever": 0.55,
      "abnormal_appearing_skin": 0.52,
      "fatigue": 0.51,
      "symptoms_of_the_face": 0.5,
    },
  },
  "Iron Deficiency Anemia": {
    prior: 0.06,
    urgency: "Low",
    description: "Anaemia from insufficient iron for haemoglobin synthesis",
    symptoms: {
      "intermenstrual_bleeding": 0.66,
      "heartburn": 0.66,
      "weakness": 0.52,
      "heavy_menstrual_flow": 0.52,
      "rectal_bleeding": 0.52,
      "fatigue": 0.51,
      "blood_in_stool": 0.5,
      "regurgitation": 0.49,
      "weight_gain": 0.49,
      "regurgitation.1": 0.49,
      "dizziness": 0.49,
    },
  },
  "Acne": {
    prior: 0.08,
    urgency: "Low",
    description: "Skin condition from clogged hair follicles causing pimples",
    symptoms: {
      "irregular_appearing_scalp": 0.69,
      "skin_dryness_peeling_scaliness_or_roughness": 0.68,
      "long_menstrual_periods": 0.67,
      "abnormal_appearing_skin": 0.55,
      "skin_rash": 0.53,
      "acne_or_pimples": 0.51,
      "skin_moles": 0.51,
      "skin_swelling": 0.5,
      "skin_growth": 0.5,
    },
  },
  "Depression": {
    prior: 0.1,
    urgency: "Moderate",
    description: "Persistent low mood, loss of interest, and impaired functioning",
    symptoms: {
      "disturbance_of_memory": 0.65,
      "abusing_alcohol": 0.52,
      "hostile_behavior": 0.52,
      "temper_problems": 0.52,
      "drug_abuse": 0.51,
      "delusions_or_hallucinations": 0.51,
      "depression": 0.5,
      "insomnia": 0.5,
      "excessive_anger": 0.5,
      "depressive_or_psychotic_symptoms": 0.49,
      "anxiety_and_nervousness": 0.49,
    },
  },
  "Ovarian Cyst": {
    prior: 0.05,
    urgency: "Moderate",
    description: "Fluid-filled sac on or inside an ovary",
    symptoms: {
      "intermenstrual_bleeding": 0.69,
      "vaginal_discharge": 0.68,
      "vomiting": 0.67,
      "lower_abdominal_pain": 0.57,
      "nausea": 0.52,
      "sharp_abdominal_pain": 0.52,
      "painful_menstruation": 0.51,
      "burning_abdominal_pain": 0.48,
      "pelvic_pain": 0.47,
    },
  },
  "Chlamydia": {
    prior: 0.05,
    urgency: "Moderate",
    description: "Common bacterial STI often asymptomatic",
    symptoms: {
      "pelvic_pain": 0.81,
      "vaginal_itching": 0.78,
      "sharp_abdominal_pain": 0.68,
      "vaginal_discharge": 0.65,
      "lower_abdominal_pain": 0.56,
      "vaginal_pain": 0.53,
    },
  },
  "Rheumatoid Arthritis": {
    prior: 0.04,
    urgency: "Moderate",
    description: "Autoimmune joint inflammation causing pain, swelling, deformity",
    symptoms: {
      "wrist_swelling": 0.68,
      "elbow_swelling": 0.67,
      "ache_all_over": 0.52,
      "wrist_pain": 0.51,
      "joint_swelling": 0.5,
      "knee_pain": 0.5,
      "joint_pain": 0.5,
      "peripheral_edema": 0.49,
      "hand_or_finger_swelling": 0.49,
      "hand_or_finger_pain": 0.47,
    },
  },
  "Gestational Diabetes": {
    prior: 0.03,
    urgency: "Moderate",
    description: "Diabetes developing during pregnancy",
    symptoms: {
      "vaginal_redness": 0.81,
      "pelvic_pressure": 0.58,
      "pain_during_pregnancy": 0.54,
      "problems_during_pregnancy": 0.54,
      "uterine_contractions": 0.54,
    },
  },
  "Schizophrenia": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Psychotic disorder affecting thinking, feeling, and behaviour",
    symptoms: {
      "insomnia": 0.67,
      "depression": 0.53,
      "hysterical_behavior": 0.52,
      "fears_and_phobias": 0.52,
      "excessive_anger": 0.52,
      "temper_problems": 0.51,
      "depressive_or_psychotic_symptoms": 0.51,
      "delusions_or_hallucinations": 0.5,
      "low_self-esteem": 0.5,
      "anxiety_and_nervousness": 0.49,
      "hostile_behavior": 0.49,
    },
  },
  "Endocarditis": {
    prior: 0.01,
    urgency: "Emergency",
    description: "Infection of the inner lining of heart chambers and valves",
    symptoms: {
      "irregular_heartbeat": 0.86,
      "palpitations": 0.84,
      "shortness_of_breath": 0.59,
      "sharp_chest_pain": 0.58,
      "dizziness": 0.52,
      "increased_heart_rate": 0.48,
    },
  },
  "Sepsis": {
    prior: 0.02,
    urgency: "Emergency",
    description: "Life-threatening organ dysfunction from infection-triggered immune response",
    symptoms: {
      "shortness_of_breath": 0.66,
      "fever": 0.54,
      "feeling_ill": 0.53,
      "difficulty_breathing": 0.51,
      "vomiting": 0.51,
      "weakness": 0.51,
      "cough": 0.51,
      "decreased_appetite": 0.5,
      "sharp_abdominal_pain": 0.5,
      "suprapubic_pain": 0.5,
      "chills": 0.5,
    },
  },
  "Cholecystitis": {
    prior: 0.03,
    urgency: "Moderate",
    description: "Inflammation of the gallbladder usually from gallstones",
    symptoms: {
      "vomiting": 0.52,
      "back_pain": 0.52,
      "side_pain": 0.52,
      "sharp_abdominal_pain": 0.51,
      "burning_abdominal_pain": 0.51,
      "symptoms_of_the_kidneys": 0.51,
      "regurgitation.1": 0.51,
      "lower_body_pain": 0.5,
      "nausea": 0.5,
      "upper_abdominal_pain": 0.49,
      "sharp_chest_pain": 0.48,
      "stomach_bloating": 0.48,
    },
  },
  "Raynaud Disease": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Exaggerated vascular response to cold or stress in extremities",
    symptoms: {
      "hand_or_finger_pain": 1.0,
      "hand_or_finger_swelling": 0.92,
      "loss_of_sensation": 0.58,
    },
  },
  "Rosacea": {
    prior: 0.03,
    urgency: "Low",
    description: "Chronic facial redness and visible blood vessels",
    symptoms: {
      "abnormal_appearing_skin": 0.67,
      "symptoms_of_eye": 0.67,
      "skin_growth": 0.52,
      "acne_or_pimples": 0.51,
      "skin_dryness_peeling_scaliness_or_roughness": 0.51,
      "skin_moles": 0.5,
      "skin_lesion": 0.5,
      "skin_swelling": 0.48,
      "lymphedema": 0.47,
      "itching_of_skin": 0.47,
    },
  },
  "Post-Traumatic Stress Disorder (PTSD)": {
    prior: 0.04,
    urgency: "Moderate",
    description: "Anxiety disorder following traumatic event exposure",
    symptoms: {
      "hostile_behavior": 0.76,
      "temper_problems": 0.53,
      "insomnia": 0.52,
      "abusing_alcohol": 0.5,
      "drug_abuse": 0.5,
      "delusions_or_hallucinations": 0.5,
      "excessive_anger": 0.49,
      "depression": 0.49,
      "depressive_or_psychotic_symptoms": 0.48,
      "anxiety_and_nervousness": 0.46,
    },
  },
  "Celiac Disease": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Autoimmune reaction to gluten damaging the small intestine",
    symptoms: {
      "peripheral_edema": 0.81,
      "sharp_chest_pain": 0.75,
      "sharp_abdominal_pain": 0.72,
      "vomiting": 0.7,
      "regurgitation.1": 0.52,
      "nausea": 0.5,
    },
  },
  "Sickle Cell Anemia": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Inherited disorder with abnormal haemoglobin causing chronic anaemia",
    symptoms: {
      "dry_lips": 0.88,
      "ache_all_over": 0.54,
      "temper_problems": 0.51,
      "pulling_at_ears": 0.51,
      "back_pain": 0.51,
      "fever": 0.5,
      "joint_pain": 0.49,
      "leg_pain": 0.46,
    },
  },
  "Hemorrhoids": {
    prior: 0.07,
    urgency: "Low",
    description: "Swollen veins in the rectum or anus causing pain and bleeding",
    symptoms: {
      "heartburn": 0.69,
      "lower_body_pain": 0.52,
      "constipation": 0.52,
      "rectal_bleeding": 0.52,
      "changes_in_stool_appearance": 0.51,
      "itching_of_the_anus": 0.5,
      "mass_or_swelling_around_the_anus": 0.5,
      "melena": 0.5,
      "blood_in_stool": 0.5,
      "pain_of_the_anus": 0.49,
      "sharp_abdominal_pain": 0.49,
    },
  },
  "Contact Dermatitis": {
    prior: 0.05,
    urgency: "Low",
    description: "Skin inflammation from direct contact with allergen or irritant",
    symptoms: {
      "skin_moles": 0.68,
      "allergic_reaction": 0.54,
      "itching_of_skin": 0.51,
      "skin_irritation": 0.51,
      "skin_dryness_peeling_scaliness_or_roughness": 0.51,
      "skin_rash": 0.5,
      "abnormal_appearing_skin": 0.5,
      "swollen_eye": 0.5,
      "skin_swelling": 0.5,
      "acne_or_pimples": 0.49,
      "skin_lesion": 0.49,
    },
  },
  "Alcoholic Liver Disease": {
    prior: 0.03,
    urgency: "Moderate",
    description: "Liver damage caused by excessive alcohol consumption",
    symptoms: {
      "abnormal_involuntary_movements": 0.78,
      "weight_gain": 0.68,
      "stomach_bloating": 0.67,
      "diarrhea": 0.65,
      "sharp_abdominal_pain": 0.54,
      "peripheral_edema": 0.52,
      "abusing_alcohol": 0.51,
    },
  },
  "Diverticulitis": {
    prior: 0.03,
    urgency: "Moderate",
    description: "Infected or inflamed pouches in the digestive tract wall",
    symptoms: {
      "constipation": 0.53,
      "sharp_abdominal_pain": 0.52,
      "lower_abdominal_pain": 0.51,
      "nausea": 0.51,
      "diarrhea": 0.51,
      "vomiting": 0.5,
      "chills": 0.5,
      "side_pain": 0.5,
      "fever": 0.49,
      "burning_abdominal_pain": 0.49,
      "blood_in_stool": 0.47,
      "upper_abdominal_pain": 0.47,
    },
  },
  "Essential Tremor": {
    prior: 0.03,
    urgency: "Low",
    description: "Neurological disorder causing rhythmic shaking",
    symptoms: {
      "hoarse_voice": 0.86,
      "dizziness": 0.73,
      "loss_of_sensation": 0.68,
      "abnormal_involuntary_movements": 0.57,
      "problems_with_movement": 0.51,
      "muscle_pain": 0.5,
      "disturbance_of_memory": 0.44,
    },
  },
  "Pneumothorax": {
    prior: 0.01,
    urgency: "Emergency",
    description: "Collapsed lung from air entering pleural space",
    symptoms: {
      "shoulder_pain": 0.74,
      "drug_abuse": 0.74,
      "side_pain": 0.56,
      "shortness_of_breath": 0.55,
      "back_pain": 0.53,
      "hurts_to_breath": 0.53,
      "cough": 0.51,
      "sharp_chest_pain": 0.49,
    },
  },
  "Human Immunodeficiency Virus Infection (HIV)": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Virus attacking immune system cells leading to AIDS",
    symptoms: {
      "drug_abuse": 1.0,
      "fears_and_phobias": 1.0,
      "nightmares": 1.0,
    },
  },
  "Mumps": {
    prior: 0.01,
    urgency: "Moderate",
    description: "Viral infection causing painful swelling of the salivary glands",
    symptoms: {
      "swollen_lymph_nodes": 0.91,
      "shoulder_swelling": 0.82,
      "ear_pain": 0.8,
      "sore_throat": 0.69,
    },
  },
  "Subarachnoid Hemorrhage": {
    prior: 0.01,
    urgency: "Emergency",
    description: "Bleeding into space between brain and surrounding membrane",
    symptoms: {
      "symptoms_of_eye": 0.84,
      "vomiting": 0.72,
      "fainting": 0.67,
      "loss_of_sensation": 0.64,
      "dizziness": 0.61,
      "headache": 0.57,
    },
  },
  "Graves Disease": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Autoimmune disorder causing hyperthyroidism",
    symptoms: {
      "irregular_heartbeat": 0.77,
      "dizziness": 0.68,
      "involuntary_urination": 0.67,
      "hemoptysis": 0.65,
      "palpitations": 0.54,
      "sweating": 0.51,
      "abnormal_involuntary_movements": 0.49,
    },
  },
  "Pleural Effusion": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Excess fluid accumulating in the pleural space around lungs",
    symptoms: {
      "sharp_abdominal_pain": 0.76,
      "weakness": 0.54,
      "rib_pain": 0.53,
      "hurts_to_breath": 0.52,
      "back_pain": 0.51,
      "side_pain": 0.49,
      "sharp_chest_pain": 0.49,
      "difficulty_breathing": 0.48,
      "cough": 0.48,
      "shortness_of_breath": 0.46,
    },
  },
  "Trigeminal Neuralgia": {
    prior: 0.01,
    urgency: "Moderate",
    description: "Sudden severe facial pain from trigeminal nerve",
    symptoms: {
      "abnormal_involuntary_movements": 0.87,
      "symptoms_of_the_face": 0.7,
      "dizziness": 0.7,
      "headache": 0.56,
      "facial_pain": 0.52,
      "pain_in_eye": 0.5,
      "toothache": 0.46,
    },
  },
  "Ankylosing Spondylitis": {
    prior: 0.02,
    urgency: "Low",
    description: "Inflammatory arthritis primarily affecting the spine",
    symptoms: {
      "paresthesia": 0.74,
      "elbow_pain": 0.52,
      "ache_all_over": 0.51,
      "low_back_pain": 0.51,
      "stiffness_all_over": 0.5,
      "knee_pain": 0.5,
      "lower_body_pain": 0.49,
      "back_pain": 0.48,
      "hip_pain": 0.47,
      "leg_pain": 0.47,
    },
  },
  "Chronic Pancreatitis": {
    prior: 0.01,
    urgency: "Moderate",
    description: "Persistent pancreatic inflammation with progressive damage",
    symptoms: {
      "skin_growth": 0.74,
      "back_pain": 0.72,
      "diarrhea": 0.71,
      "nausea": 0.59,
      "vomiting": 0.56,
      "abusing_alcohol": 0.55,
      "sharp_abdominal_pain": 0.53,
      "ache_all_over": 0.53,
    },
  },
  "Genital Herpes": {
    prior: 0.04,
    urgency: "Moderate",
    description: "Sexually transmitted infection caused by herpes simplex virus",
    symptoms: {
      "skin_lesion": 0.74,
      "vaginal_itching": 0.72,
      "suprapubic_pain": 0.71,
      "vaginal_discharge": 0.71,
      "recent_pregnancy": 0.69,
      "skin_rash": 0.56,
      "painful_urination": 0.55,
    },
  },
  "Gallstone": {
    prior: 0.05,
    urgency: "Moderate",
    description: "Hardened deposits in the gallbladder causing biliary colic",
    symptoms: {
      "regurgitation.1": 0.67,
      "back_pain": 0.53,
      "burning_abdominal_pain": 0.52,
      "nausea": 0.52,
      "upper_abdominal_pain": 0.52,
      "sharp_abdominal_pain": 0.51,
      "lower_body_pain": 0.51,
      "side_pain": 0.51,
      "heartburn": 0.5,
      "vomiting": 0.49,
      "sharp_chest_pain": 0.48,
    },
  },
  "Multiple Sclerosis": {
    prior: 0.01,
    urgency: "Moderate",
    description: "Immune system attacking the protective myelin of nerve fibers",
    symptoms: {
      "abnormal_involuntary_movements": 0.67,
      "leg_weakness": 0.54,
      "loss_of_sensation": 0.54,
      "fatigue": 0.52,
      "weakness": 0.51,
      "disturbance_of_memory": 0.51,
      "problems_with_movement": 0.51,
      "paresthesia": 0.5,
      "headache": 0.49,
      "dizziness": 0.49,
      "focal_weakness": 0.48,
    },
  },
  "Ulcerative Colitis": {
    prior: 0.02,
    urgency: "Moderate",
    description: "Chronic inflammatory bowel disease limited to the colon",
    symptoms: {
      "swollen_lymph_nodes": 0.8,
      "nausea": 0.53,
      "vomiting": 0.52,
      "sharp_abdominal_pain": 0.52,
      "lower_abdominal_pain": 0.5,
      "blood_in_stool": 0.5,
      "rectal_bleeding": 0.48,
      "diarrhea": 0.47,
      "burning_abdominal_pain": 0.46,
    },
  },
  "Hpv": {
    prior: 0.06,
    urgency: "Moderate",
    description: "Human papillomavirus causing warts and cancer risk",
    symptoms: {
      "involuntary_urination": 1.0,
      "vaginal_itching": 0.92,
      "warts": 0.54,
    },
  },
  "Diabetic Ketoacidosis": {
    prior: 0.01,
    urgency: "Emergency",
    description: "Life-threatening complication of diabetes with high ketones",
    symptoms: {
      "frequent_urination": 0.68,
      "decreased_appetite": 0.67,
      "nausea": 0.54,
      "sharp_abdominal_pain": 0.51,
      "fluid_retention": 0.51,
      "sharp_chest_pain": 0.51,
      "vomiting": 0.51,
      "diarrhea": 0.51,
      "weakness": 0.49,
      "depressive_or_psychotic_symptoms": 0.49,
    },
  },
  "Obsessive Compulsive Disorder (OCD)": {
    prior: 0.03,
    urgency: "Moderate",
    description: "Intrusive thoughts driving repetitive compulsive behaviours",
    symptoms: {
      "feeling_ill": 0.79,
      "lack_of_growth": 0.66,
      "low_self-esteem": 0.51,
      "anxiety_and_nervousness": 0.51,
      "depression": 0.5,
      "depressive_or_psychotic_symptoms": 0.5,
      "hostile_behavior": 0.5,
      "temper_problems": 0.49,
      "obsessions_and_compulsions": 0.48,
    },
  },
  "Epilepsy": {
    prior: 0.04,
    urgency: "Emergency",
    description: "Neurological disorder with recurrent unprovoked seizures",
    symptoms: {
      "lack_of_growth": 0.8,
      "abnormal_involuntary_movements": 0.53,
      "disturbance_of_memory": 0.53,
      "seizures": 0.51,
      "difficulty_speaking": 0.45,
      "muscle_weakness": 0.45,
      "headache": 0.43,
    },
  },
  "Shingles (Herpes Zoster)": {
    prior: 0.03,
    urgency: "Moderate",
    description: "Reactivation of chickenpox virus causing painful skin rash",
    symptoms: {
      "sharp_chest_pain": 0.81,
      "headache": 0.73,
      "skin_rash": 0.59,
      "skin_lesion": 0.59,
      "back_pain": 0.54,
      "itching_of_skin": 0.54,
      "abnormal_appearing_skin": 0.54,
      "facial_pain": 0.53,
      "pain_in_eye": 0.53,
    },
  },
  "Viral Hepatitis": {
    prior: 0.04,
    urgency: "Moderate",
    description: "Liver inflammation caused by hepatitis viruses A, B, C, D, or E",
    symptoms: {
      "hand_or_finger_stiffness_or_tightness": 0.8,
      "abusing_alcohol": 0.71,
      "melena": 0.57,
      "sharp_abdominal_pain": 0.54,
      "stomach_bloating": 0.51,
    },
  },
  "Peripheral Arterial Disease": {
    prior: 0.03,
    urgency: "Moderate",
    description: "Narrowed arteries reducing blood flow to limbs",
    symptoms: {
      "symptoms_of_the_kidneys": 0.65,
      "leg_cramps_or_spasms": 0.58,
      "skin_lesion": 0.56,
      "feeling_cold": 0.53,
      "lymphedema": 0.52,
      "leg_pain": 0.51,
      "poor_circulation": 0.5,
      "foot_or_toe_pain": 0.47,
    },
  },
  "Heart Failure": {
    prior: 0.05,
    urgency: "Moderate",
    description: "Heart unable to pump sufficient blood to meet body demands",
    symptoms: {
      "cough": 0.68,
      "palpitations": 0.52,
      "difficulty_breathing": 0.52,
      "sharp_chest_pain": 0.51,
      "hurts_to_breath": 0.51,
      "weight_gain": 0.51,
      "leg_swelling": 0.5,
      "fluid_retention": 0.5,
      "chest_tightness": 0.49,
      "weakness": 0.49,
      "shortness_of_breath": 0.49,
    },
  },
  "Herniated Disk": {
    prior: 0.05,
    urgency: "Low",
    description: "Spinal disc material pressing on adjacent nerve roots",
    symptoms: {
      "arm_pain": 0.66,
      "low_back_pain": 0.53,
      "paresthesia": 0.52,
      "back_pain": 0.52,
      "neck_pain": 0.51,
      "loss_of_sensation": 0.51,
      "hip_pain": 0.5,
      "leg_pain": 0.5,
      "leg_weakness": 0.49,
      "shoulder_pain": 0.49,
      "arm_weakness": 0.48,
    },
  },
  "Pulmonary Embolism": {
    prior: 0.02,
    urgency: "Emergency",
    description: "Blood clot blocking arteries in the lungs",
    symptoms: {
      "leg_pain": 0.69,
      "sharp_chest_pain": 0.53,
      "cough": 0.52,
      "side_pain": 0.51,
      "difficulty_breathing": 0.51,
      "sweating": 0.51,
      "leg_swelling": 0.51,
      "shortness_of_breath": 0.51,
      "hemoptysis": 0.5,
      "weakness": 0.5,
      "chest_tightness": 0.49,
    },
  },
  "Eczema": {
    prior: 0.07,
    urgency: "Low",
    description: "Chronic inflammatory skin condition causing itching and rash",
    symptoms: {
      "itching_of_skin": 0.52,
      "skin_lesion": 0.51,
      "acne_or_pimples": 0.51,
      "skin_swelling": 0.51,
      "skin_rash": 0.51,
      "warts": 0.51,
      "irregular_appearing_scalp": 0.5,
      "skin_irritation": 0.5,
      "allergic_reaction": 0.5,
      "abnormal_appearing_skin": 0.5,
      "skin_dryness_peeling_scaliness_or_roughness": 0.49,
      "cough": 0.49,
    },
  },
};

export const EMERGENCY_RULES = [
  {
    name: "Chest Pain + Shortness of Breath",
    symptoms: ["chest_pain", "shortness_of_breath"],
    match: "any",
    message: "Chest pain with breathing difficulty — possible cardiac event. Call emergency services immediately.",
  },
  {
    name: "Confusion + Fever",
    symptoms: ["fever", "confusion"],
    match: "all",
    message: "Confusion with fever may indicate severe infection or meningitis. Seek emergency care.",
  },
  {
    name: "Loss of Consciousness",
    symptoms: ["loss_of_consciousness"],
    match: "any",
    message: "Loss of consciousness is a medical emergency. Call emergency services now.",
  },
  {
    name: "Bluish Lips",
    symptoms: ["bluish_lips"],
    match: "any",
    message: "Cyanosis (bluish lips/fingertips) indicates severe oxygen deficiency. Emergency care required.",
  },
  {
    name: "Uncontrolled Bleeding",
    symptoms: ["uncontrolled_bleeding"],
    match: "any",
    message: "Uncontrolled bleeding requires immediate emergency care.",
  },
  {
    name: "High Fever in Infant",
    symptoms: ["fever"],
    match: "any",
    age_max: 2,
    message: "High fever in infants under 2 years requires immediate medical evaluation.",
  },
  {
    name: "Severe Abdominal Pain + Vomiting + Fever",
    symptoms: ["abdominal_pain", "vomiting", "fever"],
    match: "all",
    message: "Triad of abdominal pain, vomiting, and fever may indicate appendicitis or peritonitis.",
  },
  {
    name: "Rapid Breathing + Confusion",
    symptoms: ["rapid_breathing", "confusion"],
    match: "all",
    message: "Rapid breathing with confusion suggests possible sepsis or respiratory failure.",
  },
  {
    name: "Sudden Severe Headache",
    symptoms: ["severe_headache"],
    match: "any",
    message: "Sudden severe headache (thunderclap) may indicate subarachnoid hemorrhage.",
  },
  {
    name: "Seizure",
    symptoms: ["seizures"],
    match: "any",
    message: "Active seizure requires emergency evaluation. Call emergency services.",
  },
  {
    name: "Slurred Speech + Weakness",
    symptoms: ["focal_weakness", "slurring_words"],
    match: "all",
    message: "Slurred speech with focal weakness — possible stroke. Act FAST. Call emergency services.",
  },
];

export const ALL_SYMPTOMS = [
  "abdominal_distention",
  "abdominal_pain",
  "abdominal_rigidity",
  "abnormal_appearing_skin",
  "abnormal_breathing_sounds",
  "abnormal_involuntary_movements",
  "abnormal_movement_of_eyelid",
  "absence_of_menstruation",
  "abusing_alcohol",
  "ache_all_over",
  "acne_or_pimples",
  "allergic_reaction",
  "ankle_pain",
  "ankle_swelling",
  "antisocial_behavior",
  "anxiety",
  "anxiety_and_nervousness",
  "apnea",
  "arm_pain",
  "arm_stiffness_or_tightness",
  "arm_swelling",
  "arm_weakness",
  "back_cramps_or_spasms",
  "back_pain",
  "bleeding_from_eye",
  "bleeding_gums",
  "blindness",
  "bloating",
  "blood_in_stool",
  "blood_in_urine",
  "bluish_lips",
  "bones_are_painful",
  "burning_abdominal_pain",
  "burning_chest_pain",
  "changes_in_stool_appearance",
  "chest_pain",
  "chest_tightness",
  "chills",
  "cloudy_eye",
  "cold_hands_feet",
  "confusion",
  "congestion",
  "congestion_in_chest",
  "constipation",
  "coryza",
  "cough",
  "coughing_up_sputum",
  "cramping",
  "decreased_appetite",
  "decreased_heart_rate",
  "dehydration",
  "delusions_or_hallucinations",
  "depression",
  "depressive_or_psychotic_symptoms",
  "diarrhea",
  "difficulty_breathing",
  "difficulty_in_swallowing",
  "difficulty_speaking",
  "difficulty_swallowing",
  "diminished_hearing",
  "diminished_vision",
  "disturbance_of_memory",
  "dizziness",
  "double_vision",
  "drug_abuse",
  "dry_lips",
  "ear_pain",
  "early_or_late_onset_of_menopause",
  "elbow_pain",
  "elbow_swelling",
  "excessive_anger",
  "excessive_urination_at_night",
  "eye_burns_or_stings",
  "eye_pain",
  "eye_redness",
  "facial_pain",
  "fainting",
  "fatigue",
  "fears_and_phobias",
  "feeling_cold",
  "feeling_ill",
  "fever",
  "fluid_retention",
  "focal_weakness",
  "foot_or_toe_pain",
  "foot_or_toe_swelling",
  "foreign_body_sensation_in_eye",
  "foul_smelling_urine",
  "frequent_urination",
  "frontal_headache",
  "hand_or_finger_pain",
  "hand_or_finger_stiffness_or_tightness",
  "hand_or_finger_swelling",
  "headache",
  "heartburn",
  "heavy_menstrual_flow",
  "hemoptysis",
  "hesitancy",
  "hip_pain",
  "hoarse_voice",
  "hostile_behavior",
  "hot_flashes",
  "hurts_to_breath",
  "hysterical_behavior",
  "impotence",
  "increased_heart_rate",
  "infertility",
  "insomnia",
  "intermenstrual_bleeding",
  "involuntary_urination",
  "irregular_appearing_scalp",
  "irregular_heartbeat",
  "itchiness_of_eye",
  "itching",
  "itching_of_skin",
  "itching_of_the_anus",
  "itchy_ears",
  "itchy_eyelid",
  "itchy_scalp",
  "jaundice",
  "joint_pain",
  "joint_swelling",
  "knee_pain",
  "knee_stiffness_or_tightness",
  "knee_swelling",
  "knee_weakness",
  "lack_of_growth",
  "lacrimation",
  "leg_cramps_or_spasms",
  "leg_lump_or_mass",
  "leg_pain",
  "leg_stiffness_or_tightness",
  "leg_swelling",
  "leg_weakness",
  "lip_swelling",
  "long_menstrual_periods",
  "loss_of_appetite",
  "loss_of_consciousness",
  "loss_of_sensation",
  "loss_of_sex_drive",
  "loss_of_smell",
  "loss_of_taste",
  "low_back_pain",
  "low_self-esteem",
  "low_urine_output",
  "lower_abdominal_pain",
  "lower_body_pain",
  "lymphedema",
  "mass_or_swelling_around_the_anus",
  "melena",
  "mild_body_ache",
  "mouth_dryness",
  "muscle_ache",
  "muscle_cramps_contractures_or_spasms",
  "muscle_pain",
  "muscle_weakness",
  "nasal_congestion",
  "nausea",
  "neck_pain",
  "neck_stiffness",
  "nightmares",
  "nosebleed",
  "obsessions_and_compulsions",
  "pain_during_intercourse",
  "pain_during_pregnancy",
  "pain_in_eye",
  "pain_in_testicles",
  "pain_of_the_anus",
  "painful_menstruation",
  "painful_urination",
  "pale_skin",
  "palpitations",
  "paresthesia",
  "pelvic_pain",
  "pelvic_pressure",
  "penile_discharge",
  "peripheral_edema",
  "plugged_feeling_in_ear",
  "poor_circulation",
  "problems_during_pregnancy",
  "problems_with_movement",
  "pulling_at_ears",
  "rapid_breathing",
  "rash",
  "rebound_tenderness",
  "recent_pregnancy",
  "rectal_bleeding",
  "red_eyes",
  "regurgitation",
  "regurgitation.1",
  "restlessness",
  "retention_of_urine",
  "rib_pain",
  "ringing_in_ear",
  "runny_nose",
  "seizures",
  "sensitivity_to_light",
  "sensitivity_to_sound",
  "severe_headache",
  "sharp_abdominal_pain",
  "sharp_chest_pain",
  "shortness_of_breath",
  "shoulder_pain",
  "shoulder_swelling",
  "side_pain",
  "skin_dryness_peeling_scaliness_or_roughness",
  "skin_growth",
  "skin_irritation",
  "skin_lesion",
  "skin_moles",
  "skin_rash",
  "skin_swelling",
  "sleepiness",
  "slurring_words",
  "sneezing",
  "sore_throat",
  "spots_or_clouds_in_vision",
  "stiffness_all_over",
  "stomach_ache",
  "stomach_bloating",
  "suprapubic_pain",
  "sweating",
  "swelling_of_scrotum",
  "swollen_abdomen",
  "swollen_eye",
  "swollen_lymph_nodes",
  "symptoms_of_bladder",
  "symptoms_of_eye",
  "symptoms_of_prostate",
  "symptoms_of_the_face",
  "symptoms_of_the_kidneys",
  "temper_problems",
  "throat_swelling",
  "too_little_hair",
  "toothache",
  "unpredictable_menstruation",
  "unusual_color_or_odor_to_urine",
  "upper_abdominal_pain",
  "uterine_contractions",
  "vaginal_discharge",
  "vaginal_itching",
  "vaginal_pain",
  "vaginal_redness",
  "vision_changes",
  "visual_aura",
  "vomiting",
  "vomiting_blood",
  "warts",
  "watery_eyes",
  "weakness",
  "weight_gain",
  "wheezing",
  "wrist_pain",
  "wrist_swelling",
];

export const EMERGENCY_SYMPTOMS = [
  "chest_pain",
  "shortness_of_breath",
  "confusion",
  "loss_of_consciousness",
  "bluish_lips",
  "uncontrolled_bleeding",
  "rapid_breathing",
  "severe_headache",
  "seizures",
  "slurring_words",
  "focal_weakness",
];